---
title: "Web Scraping"
subtitle: "Examples in R"
author: "Oliver Hauke"
date: "2023-01-18"
output: 
  html_document:
    code_folding: show
    toc: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Intro

See:

- https://github.com/ggSamoora/TutorialsBySamoora/blob/main/Salary_Scraper.R#L22 
- https://github.com/ggSamoora/TutorialsBySamoora
- https://www.w3schools.com/xml/xpath_intro.asp


Needed?

- https://stackoverflow.com/questions/46202062/i-got-error-like-error-in-if-file-accessphantompath-1-0-argument-is-o

Rem.: For RSelenium a installation of Java is needed and its .exe has to be in PATH.

```{r test, eval = FALSE}
driver2 = remoteDriver$new(port = netstat::free_port())
driver2$open()
```



## Use Cases 

### Dashboard Deutschland

```{r scrape_dd, eval = FALSE}
library(RSelenium)
driver = rsDriver(
  browser = "firefox",
  port = netstat::free_port()
  ,verbose = FALSE
  )

?remoteDriver

remDr = driver$client
remDr$open()
remDr$maxWindowSize()
remDr$navigate("https://www.dashboard-deutschland.de")

#?rsDriver

remDr$findElement(using = "xpath", "//button[@aria-label='Akzeptieren']")$clickElement()


remDr$findElements(using = "class name", "highcharts-button-symbol")[[1]]$clickElement()
remDr$findElements(using = "class name", "highcharts-menu-item")[[1]]$clickElement()



show_buttons = remDr$findElements(
  using = "xpath",
  "//button[@aria-label = 'Menü des Indikators einblenden']"
)#[[1]]$clickElement()



for (button in show_buttons){
  print(
    button$getElementAttribute("class")[[1]]
  )
  button$clickElement()
  
  Sys.sleep(2)
  
  remDr$findElements(
  using = "xpath",
  './/*[contains(text(), "Anhang herunterladen")]')[[1]]$clickElement()
  
  Sys.sleep(5)
}




```

### Autoscout

```{r scraping, eval = FALSE}
library(RSelenium)
library(purrr)
driver = rsDriver(
  browser = "firefox",
  port = netstat::free_port(),
  verbose = FALSE
  )

#see ?remoteDriver
remDr = driver$client
remDr$open()
remDr$maxWindowSize()
remDr$navigate("https://www.autoscout24.de")

# Cookies ...
#/html/body/div[1]/div[2]/section[1]/div[1]/div/section/div[2]/section/div[2]/div/div[1]/select/optgroup[1]/option[1]
# el = remDr$findElement(using = "xpath", '//select[@id = "make"]/option[@value = "Volkswagen"]')
# el$clickElement()
# 
# el2 = remDr$findElement(using = 'xpath', value = '//option[@value = "Volkswagen"]')
# el2$clickElement()

#remDr$erefresh()
#remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")
# clean up

#instead: manuell

texts = c()
arts_links = c()
#cond = TRUE

for(i in 1:20){
  arts_links = c(arts_links,remDr$findElements(using = "xpath", "//div[@class = 'ListItem_wrapper__J_a_C']/div[2]/a") %>% 
  lapply( function(x)x$getElementAttribute("href") [[1]][[1]]) %>% flatten_chr())

  arts = remDr$findElements(using = "css", "article")
  texts = arts %>% 
    lapply(function(x)x$getElementText()[[1]]) %>% unlist() %>%
    c(texts, .)
  
  next_button = remDr$findElement(using = "xpath", "//button[@aria-label = 'Zu nächsten Seite']")
  next_button$clickElement()
  Sys.sleep(10)
  
  #remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")
}



# vtype = c()
# vlabel = c()
# price_label = c()
# price = c()
# make = c()
# seller = c()
# plz = c()
# mileage = c()
# fuel = c()
# model = c()
# date = c()
# texts = c()
# arts_links = c()
# 
# 
# 
# 
# 
# art = arts[[2]]
# 
# 
# 
# texts = c(texts, arts[[1]]$getElementText())
# 
# art$getElementAttribute("data-model")[[1]]
# 
# arts[[2]]$getElementAttribute()
# 
# 
# 
# arts[[2]]$getElementAttribute("/div[@class = 'ListItem_wrapper__J_a_C']/div[2]/a")
# #/html/body/div[2]/div[2]/div/div/div/div[4]/div[2]/main/article[2]/div[1]/div[2]/a
# links = 
# 
# 
# 
# remDR$find
# 
# $getElementText()

remDr$close()
driver[["server"]]$stop()
gc()

dat = tibble::tibble(text = texts, link = arts_links)

dat = dat %>% 
  distinct(text,.keep_all = TRUE) %>% 
  distinct(link,.keep_all = TRUE)


write.csv2(dat, paste0("../../data/", Sys.Date(), "-VW_raw.csv"), row.names = FALSE)
```
